# -*- coding: utf-8 -*-
from . import common
from . import res_company
from . import res_bank
from . import res_partner_bank
from . import res_partner
from . import res_users
from . import res_config_settings
from . import ir_attachment
from . import mail_template
from . import mail_compose_message
from . import stock_picking
from . import stock_scrap
from . import sale_order
from . import product_template
from . import sale_order_line
from . import account_move
from . import project_project
from . import project_task
from . import tta_packages
from . import sale_order_tta_package_line
from . import sale_annex
from . import purchase_order
from . import ir_actions_report
from . import sale_contract_template
from . import sale_addendum_template
from . import hr_leave
from . import crm_opportunity_type
from . import crm_equipment_type
from . import crm_lead
from . import project_worksheet_line