# -*- coding: utf-8 -*-
{
    'name': "IKMA Addons",
    'summary': "Addons for IKMA MMC",
    'description': """
Addons for IKMA MMC
    """,
    'author': "ERPGO",
    'website': "https://www.erpgo.az",
    'category': 'Uncategorized',
    'version': '18.0',
    'depends': ['base','sale_management',
                'project','sale_project','account',
                'stock', 'purchase', 'sale_subscription',
                'hr_holidays', 'crm', 'sale_pdf_quote_builder', 
                'account_reports', 'industry_fsm_report'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        
        'data/ir_actions_server_views.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        
        'views/product_template.xml',
        'views/sale_order.xml',
        'views/sale_order_line.xml',
        'views/sale_contract_info.xml',
        'views/stock_picking.xml',
        'views/stock_scrap.xml',
        'views/res_config_settings.xml',
        'views/res_company.xml',
        'views/res_bank.xml',
        'views/res_partner_bank.xml',
        'views/res_users.xml',
        'views/res_partner.xml',
        'views/project_task.xml',
        'views/account_move.xml',
        'views/tta_packages.xml',
        'views/sale_annex.xml',
        'views/purchase_order.xml',
        'views/project_project.xml',
        'views/sale_contract_template.xml',
        'views/sale_addendum_template.xml',
        'views/sale_subscription.xml',
        'views/mail_template.xml',
        'views/crm_opportunity_type.xml',
        'views/crm_equipment_type.xml',
        'views/crm_lead.xml',
        'views/hr_leave.xml',

        'data/ir_actions_act_window_views.xml',
        'data/ir_ui_menu_views.xml',
        
        'wizard/tta_report_wizard.xml',
        'wizard/annex_report_wizard.xml',
        'wizard/crm_lead_to_opportunity.xml',
        'wizard/crm_lead_to_opportunity_mass.xml',
    
        'layouts/annex_layout_boxed.xml',
        'layouts/contract_layout.xml',
        'layouts/addendum_layout.xml',
        'layouts/tta_layout_boxed.xml',
        'layouts/commercial_offer_layout_boxed.xml',

        'templates/external_layout_boxed_inherit.xml',
        'templates/web_address_layout_inherit.xml',
        'templates/report_saleorder_document.xml',
        'templates/annex_templates.xml',
        'templates/contract_templates.xml',
        'templates/commercial_offer_templates.xml',
        'templates/tta_templates.xml',
        'templates/invoice_templates.xml',
        'templates/hr_leave_templates.xml',
        'templates/pdf_export_main_customer_report.xml',
        
        'reports/paperformats.xml',
        'reports/contract_template_report.xml',
        'reports/tta_template_report.xml',
        'reports/annex_template_report.xml',
        'reports/commercial_offer_template_report.xml',
        'reports/invoice_template_reports.xml',
        'reports/hr_leave_reports.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'application': True,
    'installable': True,
    'auto_install': False,
}
